automode:
  enabled: true
  interval: 60
round:
  duration: 5
  multiplier: 10
messages:
  round:
    start: "Round #<<roundNumber>> started!"
    end: "Round #<<roundNumber>> ended!"
    status:
      statusMessage: "Game #<<roundNumber>> is <<status>>"
      running: "running"
      halted: "halted"
      ended: "finished"
    winningNumber: "Winning number is <<winningNumber>>!"
    winners: "Winner(s):"
    noWinners: "Nobody won :("
  ticket:
    bought: "You succesfully bought a ticket. Your lucky number is <<luckyNumber>>!"
    failure: "Couldn't buy ticket with lucky number <<luckyNumber>>"
