# If enabled, lottery rounds are started and stopped automatically
autoMode:
  enabled: true
  # Intervals for a round/the break between two rounds in seconds
  roundInterval: 120
  breakInterval: 30

# Defines round settings
round:
  # The winner gets his bet * multiplier as a reward
  multiplier: 10
  # Defines the range for the ticket numbers
  numberRange:
    min: 100
    max: 999
  priceRange:
    min: 1
    max: 16
  allowSameTicketNumbers: true
  allowMoreThanOneEntryPerPlayer: true

# List of allowed blocks that can be used to bet
# A complete list can be found under:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
allowedBlocks:
  - "diamond"
  - "gold_nugget"
  - "gold_ingot"

# Messages that can be seen by players
messages:
  round:
    start: "Round #<<roundNumber>> started!"
    end: "Round #<<roundNumber>> ended!"
    time:
      nextBreak: "Round #<<roundNumber>> ends in <<seconds>>s"
      nextRound: "New round starts in <<seconds>>s"
    status:
      statusMessage: "Round #<<roundNumber>> is <<status>>"
      running: "running."
      halted: "halted."
      finished: "over."
      startsSoon: "Round #<<roundNumber>> starts in <<seconds>>s"
      stopsSoon: "Round #<<roundNumber>> stops in <<seconds>>s"
    winningNumber: "Winning number is <<winningNumber>>!"
    winners: "Winner(s):"
    noWinners: "Nobody won :("
  ticket:
    bought: "You succesfully bought a ticket. Your ticket number is <<ticketNumber>>!"
    list: "Bought tickets:"
    error:
      general: "Couldn't buy ticket."
      wrongNumberRange: "It seems like <<ticketNumber>> is too small/big. The allowed range is: <<min>>-<<max>>"
      wrongPriceRange: "It seems like <<playerPrice>> is too small/big. The allowed range is: <<min>>-<<max>>"
      alreadyExists: "Looks like <<ticketNumber>> is already taken by someone else."
      tooMany: "Looks like you've already bought a ticket."
      tooPoor: "It seems like you can't afford <<amount>> <<material>>(S) :("
      reward: "Could not give you your reward. Is your inventory full?"
  permissionError: "You do not have permission to do that!"
