autoMode:
  enabled: true
  interval: 60
round:
  duration: 5
  multiplier: 10
# List of allowed blocks can be found under:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
allowedBlocks:
  - "diamond"
  - "gold_nugget"
  - "gold_ingot"
messages:
  round:
    start: "Round #<<roundNumber>> started!"
    end: "Round #<<roundNumber>> ended!"
    status:
      statusMessage: "Game #<<roundNumber>> is <<status>>"
      running: "running."
      halted: "halted."
      ended: "over."
    winningNumber: "Winning number is <<winningNumber>>!"
    winners: "Winner(s):"
    noWinners: "Nobody won :("
  ticket:
    bought: "You succesfully bought a ticket. Your ticket number is <<ticketNumber>>!"
    list: "Bought tickets:"
    error:
      general: "Couldn't buy ticket with ticket number <<ticketNumber>>."
      alreadyExists: "Looks like <<ticketNumber>> is already taken by someone else."
      tooMany: "Looks like you've already bought a ticket."
      roundOver: "Couldn't buy ticket because there's no active round right now."
      tooPoor: "It seems like you can't afford <<amount>> <<material>>(S) :("
      reward: "Could not give you your reward. Is your inventory full?"
  permissionError: "You do not have permission to do that!"
